name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Change directory
      run: cd ../terraform

    - name: Initialize Terraform
      run: terraform init

    # Add more steps for other Terraform commands (e.g., plan, apply)
